name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-23"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjRkZTJlYWUtYTY1MC00ZjdlLWE0MmUtNmQwZmVhOGJlMWYyIiwidGVuYW50X2lkIjoiMDhiODE4Njk3YmJiNThkODZlNzQyYzBmMWI0MGEzYTk3NDQwNzNjNTQ3ZWYxN2MyNDZlYTMyNDk1NjUyNDNmNCIsImludGVybmFsX3NlY3JldCI6IjFkMGM5NGM1LTk2NWItNGEzMC04ODNmLTQzZGQyOGQzN2MxYyJ9.wKnxnzrg23HQWHL-hWSfvJDUJWpkunoJvWzjmazCjro"

